CFLAGS = -O3 -I.
CC = gcc

TARGETS = test00 test01 test02 test03 test04 test05 test06 test07 test08 test09 \
	test10 test11 test12 test13 test14 test15 test16 test17

all:
	$(CC) $(CFLAGS) -o test00 test00.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test01 test01.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test02 test02.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test03 test03.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test04 test04.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test05 test05.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test06 test06.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test07 test07.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test08 test08.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test09 test09.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test10 test10.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test11 test11.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test12 test12.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test13 test13.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test14 test14.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test15 test15.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test16 test16.c -lmcersa -lz
	$(CC) $(CFLAGS) -o test17 test17.c -lmcersa -lz


clean:
	rm -f $(TARGETS) mce.key mce.pub crmce.key crmce.pub
